---
title: |
  河南省\
  肿瘤登记质量控制报告
subtitle: "第一季度"
date: today
registry: "河南省肿瘤登记处"
header: "质控报告"
footer: "https://chenq.site"
section-numbering: "1."
authors:
  - name: 陈 琼
    email: chenq08@126.com
    affiliation: "河南省肿瘤医院"
mainfont: "song"
format:
  qcreport-typst: default
---

## 人口情况

*TODO* Create an example file that demonstrates the formatting and features of your format.
*TODO* Create an example file that demonstrates the formatting and features of your format.
*TODO* Create an example file that demonstrates the formatting and features of your format.
*TODO* Create an example file that demonstrates the formatting and features of your format.

*TODO* Create an example file that demonstrates the formatting and features of your format.
*TODO* Create an example file that demonstrates the formatting and features of your format.
*TODO* Create an example file that demonstrates the formatting and features of your format.
*TODO* Create an example file that demonstrates the formatting and features of your format.

## 发病情况

## 死亡情况

You can learn more about creating custom Typst templates here: 

<https://quarto.org/docs/prerelease/1.4/typst.html#custom-formats>

### fjkdajlkfdj
kjladjslakjfldajlfdjsa



